[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.76.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "https://at.shoogle.net"
  status = 302
  conditions = {Country = ["at"]}

[[redirects]]
  from = "/"
  to = "https://ch.shoogle.net"
  status = 302
  conditions = {Country = ["ch"]}

[[redirects]]
  from = "/"
  to = "https://de.shoogle.net"
  status = 302
  conditions = {Country = ["de"]}

[[redirects]]
  from = "/"
  to = "https://us.shoogle.net"
  status = 302
  conditions = {Country = ["us"]}
