[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.76.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "https://at.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["at"]}

[[redirects]]
  from = "/"
  to = "https://au.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["au"]}

[[redirects]]
  from = "/"
  to = "https://ca.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["ca"]}

[[redirects]]
  from = "/"
  to = "https://ch.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["ch"]}

[[redirects]]
  from = "/"
  to = "https://de.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["de"]}

[[redirects]]
  from = "/"
  to = "https://gb.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["gb"]}

[[redirects]]
  from = "/"
  to = "https://ie.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["ie"]}

[[redirects]]
  from = "/"
  to = "https://in.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["in"]}

[[redirects]]
  from = "/"
  to = "https://nz.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["nz"]}

[[redirects]]
  from = "/"
  to = "https://ph.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["ph"]}

[[redirects]]
  from = "/"
  to = "https://pk.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["pk"]}

[[redirects]]
  from = "/"
  to = "https://us.shoogle.net"
  status = 301
  force = true
  conditions = {Country = ["us"]}
